### ISSUE TITLE
SyntaxError from library

### ISSUE THREAD

**Issue by MacroMan** [peterdemartini/html5-to-pdf#37]
Version 3.0.1 has the following fatal SyntaxError in lib/index.js:35

node_modules/html5-to-pdf/lib/index.js:35
    )
    ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (api/components/documenter.js:3:21)

**Comment by PaganiLover** [comment]
I am getting a similar error. The version I am using is 4.1.2.

**Comment by PaganiLover** [comment]
@MacroMan and @peterdemartini I found the issue. There is an unnecessary comma in the index.js file (line 36). The file path is /node_modules/html5-to-pdf/lib/index.js:36. By removing the comma everything appeared to function properly.
