### ISSUE TITLE
Docker image fails to launch chrome with the documented docker method.

### ISSUE THREAD

**Issue by thommiller** [peterdemartini/html5-to-pdf#50]
html5-to-pdf Version: 3.2.0
docker version: 18.09.0

Using the current build, I clone the repo, cd into it and run:
```
docker build -t local/html5-to-pdf-example -f examples/Dockerfile .
docker run --rm -i --cap-add=SYS_ADMIN local/html5-to-pdf-example
```
Which first fails with missing dependency issues, so I modify `examples/Dockerfile:14`, from:
```
RUN npm install puppeteer
```
to 
```
RUN npm install puppeteer auto-bind lodash
```
Which makes the image build successfully, but on run we see the following stack trace:
```
Successfully tagged local/html5-to-pdf-example:latest
Error: Failed to launch chrome!
Error relocating /usr/lib/chromium/chrome: hb_font_set_variations: symbol not found
Error relocating /usr/lib/chromium/chrome: hb_font_funcs_set_glyph_h_advances_func: symbol not found
Error relocating /usr/lib/chromium/chrome: hb_face_get_table_tags: symbol not found
Error relocating /usr/lib/chromium/chrome: hb_font_set_ptem: symbol not found
Error relocating /usr/lib/chromium/chrome: hb_aat_layout_feature_type_get_selector_infos: symbol not found
Error relocating /usr/lib/chromium/chrome: hb_ot_tags_from_script_and_language: symbol not found
Error relocating /usr/lib/chromium/chrome: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2ERKS4_mRKS3_: symbol not found
Error relocating /usr/lib/chromium/chrome: hb_aat_layout_get_feature_types: symbol not found
Error relocating /usr/lib/chromium/chrome: hb_ot_layout_table_select_script: symbol not found


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/node_modules/puppeteer/lib/Launcher.js:349:14)
    at Interface.helper.addEventListener (/node_modules/puppeteer/lib/Launcher.js:338:50)
    at Interface.emit (events.js:185:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:152:10)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
TypeError: Cannot read property 'pdf' of undefined
    at HTML5ToPDF.build (/app/lib/index.js:96:33)
    at run (/app/examples/example-docker.js:21:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
DONE
TypeError: Cannot read property 'close' of undefined
    at HTML5ToPDF.close (/app/lib/index.js:103:24)
    at run (/app/examples/example-docker.js:22:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

I believe this is due to the headless chrome not finding X server, but I was under the impression this must have been working at some point (as it is documented).

Let me know if you need any more info in reproducing this issue.
Thanks.

**Comment by peterdemartini** [comment]
This should be fixed now. I added it to CI so we don't run into this again.
